scheme: Gemini

motion:
  enable: false

custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl
  bodyEnd: source/_data/body-end.njk
  footer: source/_data/footer.njk

avatar:
  url: /images/profile/avatar.png
  rounded: true
  rotated: false

social:
  有澤法律事務所: https://stellexlaw.com/ || fa fa-building
  Threads: https://www.threads.com/@han0302 || fa fa-at
  GitHub: https://github.com/han0302-cyber || fab fa-github
  司法院裁判書閱讀助手: https://chromewebstore.google.com/detail/nigjaldhpljkcgedolepmhmifaplpadn || fab fa-chrome

social_icons:
  enable: true
  icons_only: false
  transition: false

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  文章: /archives/ || fa fa-archive

local_search:
  enable: true
  top_n_per_article: 1
  unescape: false
  preload: false

menu_settings:
  icons: true
  badges: false

footer:
  copyright: Ting-Han Lin

busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
